name: Deploy Data Factory

on:
  workflow_dispatch:
    inputs:
      # global configuration
      packageJsonFolder:
        default: build
        required: true
        description: 'packageJsonFolder'
      adfRootFolder: 
        default: /
        required: true
        description: 'adfRootFolder'
      globalParametersFolder: 
        default: globalParameters
        required: true
        description: 'globalParametersFolder'
      overridesFolder: 
        default: overrides
        required: true
        description: 'overridesFolder'

#trigger:
#  branches:
#    include:
#    - main # source data factory collaboration branch
#  paths:
#    exclude:
#    - docs
#    - pipelines

jobs:
  initialisation:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise environment variables
        id: initialise
        run: |
          if [[ "${{github.ref}}" == "refs/heads/master" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=globalParameterFileName:./datafactory/globalParameters/ADF_GlobalParameters_PROD.json"
            echo "::set-output name=overridesFileName:./datafactory/overrides/ADF_Overrides_PROD.json"
            echo "::set-output name=something:prd"
            echo "::set-output name=devTriggers:enabled"
            echo "::set-output name=dataFactoryName:helloworld"
            echo "PRODUCTION DEPLOYMENT SELECTED"
          else
            echo "Running outside of standard production branches. Using development variables"
            echo "::set-output name=globalParameterFileName:./datafactory/globalParameters/ADF_GlobalParameters_DEV.json"
            echo "::set-output name=overridesFileName:./datafactory/overrides/ADF_Overrides_DEV.json"
            echo "::set-output name=something:dev"
            echo "::set-output name=devTriggers:disabled"
            echo "DEVELOPMENT DEPLOYMENT SELECTED"
          fi
      - name: test
        run: echo ${{ steps.initialise.outputs.overridesFileName}}
          
          
          
    outputs:
      subscriptionId: c308076f-746c-4134-94d5-74f88630c621
      globalParameterFileName: ${{ steps.initialise.outputs.globalParameterFileName }}
      overridesFileName: ${{ steps.initialise.outputs.overridesFileName}}
      svcConnection: ${{ steps.initialise.outputs.ENV}}-svcConnection
      resourceGroupName: ${{ steps.initialise.outputs.ENV}}-radp-syd-rg
      deploymentName: ArmTemplateForFactory_${{ steps.initialise.outputs.ENV}}
      dataFactoryName: ${{ steps.initialise.outputs.ENV}}-radp-syd-adf
      dataFactoryName2: ${{ steps.initialise.outputs.dataFactoryName}}
      selfHostedRuntimeLinkedId: ${{ steps.initialise.outputs.ENV}}-linked-runtime-resource-id
      disableTriggers: ${{ steps.initialise.outputs.devTriggers}}

